apiVersion: v2
name: ghost
description: |
  Helm chart untuk ghost service.
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: common-library
    version: "1.0.0"
    repository: "oci://registry-1.docker.io/sfirman87"
    # Untuk dev lokal:
    # repository: "file://../commonLibrary"
